#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>
#include <cublas_v2.h>
#include <cmath>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <limits>
#include <new>
#include <vector>

namespace {
constexpr int D=384,I=1536,H=12,HD=32,LAYERS=12,PARAMS=197;
constexpr int FP32=0,FP16=1,BF16=2;
enum Stage {STAGE_EMBEDDINGS=1,STAGE_EMBEDDING_LN=2,STAGE_Q=3,STAGE_K=4,STAGE_V=5,STAGE_SCORES=6,STAGE_SOFTMAX=7,STAGE_CONTEXT=8,STAGE_ATTENTION_OUTPUT=9,STAGE_ATTENTION_LN=10,STAGE_FFN_INPUT=11,STAGE_GELU=12,STAGE_FFN_OUTPUT=13,STAGE_FFN_LN=14,STAGE_CLS=15,STAGE_L2=16};
struct InvalidValue {int category=0,stage=0,layer=-1;unsigned long long index=0;float value=0;};

struct Model {
    void* p[PARAMS]{};size_t n[PARAMS]{};cublasHandle_t blas{};cudaStream_t stream{};bool ready=false;int precision=FP32;
    int64_t *di=nullptr,*dt=nullptr;uint8_t* dm=nullptr;
    void *a=nullptr,*b=nullptr,*q=nullptr,*k=nullptr,*v=nullptr,*merged=nullptr,*tmp=nullptr,*inter=nullptr;float* result=nullptr;
    size_t row_capacity=0,batch_capacity=0;cudaGraph_t graph{};cudaGraphExec_t graph_exec{};int graph_batch=0,graph_seq=0,math_mode=0;bool graph_enabled=true,graph_warmed=false;
    uint64_t forward_mallocs=0,forward_frees=0,kernel_launches=0,parameter_uploads=0,workspace_reallocations=0,h2d_bytes=0,d2h_bytes=0,synchronizations=0;
    uint64_t graph_launches=0,internal_submissions=0,graph_captures=0,graph_invalidations=0,parameter_bytes=0,workspace_bytes=0,conversion_ns=0,upload_ns=0,validation_ns=0,transpose_ns=0;
    int last_batch=0,last_seq=0;bool last_graph_captured=false,last_graph_reused=false;
};

bool ok(cudaError_t value){return value==cudaSuccess;}bool okb(cublasStatus_t value){return value==CUBLAS_STATUS_SUCCESS;}
size_t element_size(const Model* m){return m->precision==FP32?sizeof(float):sizeof(uint16_t);}

template<class T> __device__ float read_value(const T* p,size_t i){return (float)p[i];}
template<> __device__ float read_value<__half>(const __half* p,size_t i){return __half2float(p[i]);}
template<> __device__ float read_value<__nv_bfloat16>(const __nv_bfloat16* p,size_t i){return __bfloat162float(p[i]);}
template<class T> __device__ void write_value(T* p,size_t i,float v){p[i]=(T)v;}
template<> __device__ void write_value<__half>(__half* p,size_t i,float v){p[i]=__float2half_rn(v);}
template<> __device__ void write_value<__nv_bfloat16>(__nv_bfloat16* p,size_t i,float v){p[i]=__float2bfloat16_rn(v);}
__device__ void record_invalid(InvalidValue* invalid,int stage,int layer,size_t index,float value){if(!invalid||isfinite(value))return;int category=isnan(value)?1:(value>0?2:3);if(atomicCAS(&invalid->category,0,category)==0){invalid->stage=stage;invalid->layer=layer;invalid->index=index;invalid->value=value;}}
template<class T> __global__ void scan_finite(const T* values,size_t count,InvalidValue* invalid,int stage,int layer){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<count)record_invalid(invalid,stage,layer,i,read_value(values,i));}
template<class T> __global__ void copy_float32(const T* values,float* output,size_t count){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<count)output[i]=read_value(values,i);}

void invalidate_graph(Model* m){bool existed=m->graph_exec||m->graph;if(m->graph_exec)cudaGraphExecDestroy(m->graph_exec);if(m->graph)cudaGraphDestroy(m->graph);if(existed)m->graph_invalidations++;m->graph_exec=nullptr;m->graph=nullptr;m->graph_batch=0;m->graph_seq=0;m->graph_warmed=false;}
void release_workspace(Model* m){invalidate_graph(m);void* allocations[]={m->di,m->dt,m->dm,m->a,m->b,m->q,m->k,m->v,m->merged,m->tmp,m->inter,m->result};for(void* p:allocations)if(p)m->forward_frees++;cudaFree(m->di);cudaFree(m->dt);cudaFree(m->dm);cudaFree(m->a);cudaFree(m->b);cudaFree(m->q);cudaFree(m->k);cudaFree(m->v);cudaFree(m->merged);cudaFree(m->tmp);cudaFree(m->inter);cudaFree(m->result);m->di=m->dt=nullptr;m->dm=nullptr;m->a=m->b=m->q=m->k=m->v=m->merged=m->tmp=m->inter=m->result=nullptr;m->row_capacity=m->batch_capacity=0;m->workspace_bytes=0;}
bool ensure_workspace(Model* m,int batch,int seq){
    if(batch<1||seq<1)return false;size_t rows=(size_t)batch*seq;if(rows>std::numeric_limits<size_t>::max()/D||rows>std::numeric_limits<size_t>::max()/I)return false;size_t attention_rows=(size_t)batch*H*seq;if(attention_rows>std::numeric_limits<size_t>::max()/(size_t)seq)return false;(void)(attention_rows*seq);
    if(rows<=m->row_capacity&&(size_t)batch<=m->batch_capacity)return true;size_t new_rows=rows>m->row_capacity?rows:m->row_capacity,new_batch=(size_t)batch>m->batch_capacity?(size_t)batch:m->batch_capacity,bytes=element_size(m);release_workspace(m);m->workspace_reallocations++;
    #define ALLOC(ptr,size) if(!ok(cudaMalloc(&(m->ptr),(size)))){release_workspace(m);return false;}else{m->forward_mallocs++;m->workspace_bytes+=(size);}
    ALLOC(di,new_rows*sizeof(int64_t));ALLOC(dt,new_rows*sizeof(int64_t));ALLOC(dm,new_rows);ALLOC(a,new_rows*D*bytes);ALLOC(b,new_rows*D*bytes);ALLOC(q,new_rows*D*bytes);ALLOC(k,new_rows*D*bytes);ALLOC(v,new_rows*D*bytes);ALLOC(merged,new_rows*D*bytes);ALLOC(tmp,new_rows*D*bytes);ALLOC(inter,new_rows*I*bytes);ALLOC(result,new_batch*D*sizeof(float));
    #undef ALLOC
    m->row_capacity=new_rows;m->batch_capacity=new_batch;return true;
}

template<class T> __global__ void embeddings(const int64_t* ids,const int64_t* types,T* out,const T* word,const T* pos,const T* type,int rows,int seq){int index=blockIdx.x*blockDim.x+threadIdx.x,total=rows*seq*D;if(index<total){int token=index/D,d=index%D;float sum=read_value(word,(size_t)ids[token]*D+d)+read_value(pos,(size_t)(token%seq)*D+d)+read_value(type,(size_t)types[token]*D+d);write_value(out,index,sum);}}
template<class T> __global__ void layer_norm(const T* a,const T* residual,T* out,const T* gamma,const T* beta,int rows){
    __shared__ double means[128],m2s[128];__shared__ int counts[128];int r=blockIdx.x,tid=threadIdx.x;if(r>=rows)return;double mean=0,m2=0;int count=0;
    for(int d=tid;d<D;d+=blockDim.x){double x=read_value(a,(size_t)r*D+d)+(residual?(double)read_value(residual,(size_t)r*D+d):0.0);count++;double delta=x-mean;mean+=delta/count;m2+=delta*(x-mean);}means[tid]=mean;m2s[tid]=m2;counts[tid]=count;__syncthreads();
    for(int offset=64;offset>0;offset/=2){if(tid<offset){int right=tid+offset,n1=counts[tid],n2=counts[right];if(n2){double delta=means[right]-means[tid],n=n1+n2;means[tid]+=delta*n2/n;m2s[tid]+=m2s[right]+delta*delta*n1*n2/n;counts[tid]=n;}}__syncthreads();}
    double inv=rsqrt(m2s[0]/D+1e-12);for(int d=tid;d<D;d+=blockDim.x){double x=read_value(a,(size_t)r*D+d)+(residual?(double)read_value(residual,(size_t)r*D+d):0.0);float result=read_value(gamma,d)*(float)((x-means[0])*inv)+read_value(beta,d);write_value(out,(size_t)r*D+d,result);}
}
template<class T> __global__ void bias(T* out,const T* values,int rows,int width){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<rows*width)write_value(out,i,read_value(out,i)+read_value(values,i%width));}
template<class T> __global__ void gelu(T* values,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n){float x=read_value(values,i);write_value(values,i,0.5f*x*(1.0f+erff(x*0.7071067811865475f)));}}
template<class T> __global__ void fused_attention(const T* q,const T* k,const T* v,const uint8_t* mask,T* merged,int batch,int seq,InvalidValue* invalid=nullptr,int layer=-1){
    __shared__ float probabilities[512],reduction[128],maximum;int row=blockIdx.x,tid=threadIdx.x,lane=tid&31,warp=tid>>5;if(row>=batch*H*seq)return;int query=row%seq,head=(row/seq)%H,b=row/(H*seq);
    for(int key=warp;key<seq;key+=4){float score=read_value(q,((size_t)b*seq+query)*D+head*HD+lane)*read_value(k,((size_t)b*seq+key)*D+head*HD+lane);for(int offset=16;offset>0;offset/=2)score+=__shfl_down_sync(0xffffffff,score,offset);if(lane==0){score*=0.1767766952966369f;if(mask[b*seq+key])record_invalid(invalid,STAGE_SCORES,layer,(size_t)row*seq+key,score);probabilities[key]=mask[b*seq+key]?score:-INFINITY;}}
    __syncthreads();float local_max=-INFINITY;for(int key=tid;key<seq;key+=blockDim.x)local_max=fmaxf(local_max,probabilities[key]);reduction[tid]=local_max;__syncthreads();for(int offset=64;offset>0;offset/=2){if(tid<offset)reduction[tid]=fmaxf(reduction[tid],reduction[tid+offset]);__syncthreads();}
    if(tid==0)maximum=reduction[0];__syncthreads();float local_sum=0;for(int key=tid;key<seq;key+=blockDim.x){float value=mask[b*seq+key]?expf(probabilities[key]-maximum):0;probabilities[key]=value;local_sum+=value;}reduction[tid]=local_sum;__syncthreads();for(int offset=64;offset>0;offset/=2){if(tid<offset)reduction[tid]+=reduction[tid+offset];__syncthreads();}if(tid==0&&(!isfinite(reduction[0])||reduction[0]<=0))record_invalid(invalid,STAGE_SOFTMAX,layer,row,reduction[0]);for(int key=tid;key<seq;key+=blockDim.x){probabilities[key]/=reduction[0];record_invalid(invalid,STAGE_SOFTMAX,layer,(size_t)row*seq+key,probabilities[key]);}__syncthreads();
    if(tid<HD){float sum=0;int d=head*HD+tid;for(int key=0;key<seq;key++)sum+=probabilities[key]*read_value(v,((size_t)b*seq+key)*D+d);record_invalid(invalid,STAGE_CONTEXT,layer,((size_t)b*seq+query)*D+d,sum);write_value(merged,((size_t)b*seq+query)*D+d,sum);}
}
template<class T> __global__ void cls_l2(const T* hidden,float* out,int batch,int seq){__shared__ double sums[128];int b=blockIdx.x,tid=threadIdx.x;if(b>=batch)return;double sum=0;for(int d=tid;d<D;d+=blockDim.x){double value=read_value(hidden,(size_t)b*seq*D+d);sum+=value*value;}sums[tid]=sum;__syncthreads();for(int offset=64;offset>0;offset/=2){if(tid<offset)sums[tid]+=sums[tid+offset];__syncthreads();}double inv=rsqrt(sums[0]);for(int d=tid;d<D;d+=blockDim.x)out[b*D+d]=(float)(read_value(hidden,(size_t)b*seq*D+d)*inv);}

template<class T> cudaDataType_t cuda_type();template<> cudaDataType_t cuda_type<__half>(){return CUDA_R_16F;}template<> cudaDataType_t cuda_type<__nv_bfloat16>(){return CUDA_R_16BF;}
template<class T> bool linear_mixed(Model* m,const T* a,const T* w,const T* b,T* c,int rows,int k,int n){const float alpha=1,beta=0;if(!okb(cublasGemmEx(m->blas,CUBLAS_OP_N,CUBLAS_OP_N,n,rows,k,&alpha,w,cuda_type<T>(),n,a,cuda_type<T>(),k,&beta,c,cuda_type<T>(),n,CUBLAS_COMPUTE_32F,CUBLAS_GEMM_DEFAULT_TENSOR_OP)))return false;bias<<<(rows*n+255)/256,256,0,m->stream>>>(c,b,rows,n);return ok(cudaGetLastError());}
bool linear_fp32(Model* m,const float* a,const float* w,const float* b,float* c,int rows,int k,int n){const float alpha=1,beta=0;if(!okb(cublasSgemm(m->blas,CUBLAS_OP_N,CUBLAS_OP_N,n,rows,k,&alpha,w,n,a,k,&beta,c,n)))return false;bias<<<(rows*n+255)/256,256,0,m->stream>>>(c,b,rows,n);return ok(cudaGetLastError());}
template<class T> bool linear_any(Model* m,const T* a,const T* w,const T* b,T* c,int rows,int k,int n){return linear_mixed(m,a,w,b,c,rows,k,n);}template<> bool linear_any<float>(Model* m,const float* a,const float* w,const float* b,float* c,int rows,int k,int n){return linear_fp32(m,a,w,b,c,rows,k,n);}
template<class T> bool launch_typed(Model* m,int batch,int seq,int rows,size_t dn){
    auto p=[&](int i){return (T*)m->p[i];};T* a=(T*)m->a;T* b=(T*)m->b;T* q=(T*)m->q;T* k=(T*)m->k;T* v=(T*)m->v;T* merged=(T*)m->merged;T* tmp=(T*)m->tmp;T* inter=(T*)m->inter;
    embeddings<<<(dn+255)/256,256,0,m->stream>>>(m->di,m->dt,tmp,p(0),p(1),p(2),batch,seq);layer_norm<<<rows,128,0,m->stream>>>(tmp,(T*)nullptr,a,p(3),p(4),rows);
    for(int layer=0;layer<LAYERS;layer++){int x=5+layer*16;if(!linear_mixed(m,a,p(x),p(x+1),q,rows,D,D)||!linear_mixed(m,a,p(x+2),p(x+3),k,rows,D,D)||!linear_mixed(m,a,p(x+4),p(x+5),v,rows,D,D))return false;fused_attention<<<batch*H*seq,128,0,m->stream>>>(q,k,v,m->dm,merged,batch,seq);if(!linear_mixed(m,merged,p(x+6),p(x+7),tmp,rows,D,D))return false;layer_norm<<<rows,128,0,m->stream>>>(tmp,a,b,p(x+8),p(x+9),rows);if(!linear_mixed(m,b,p(x+10),p(x+11),inter,rows,D,I))return false;gelu<<<((size_t)rows*I+255)/256,256,0,m->stream>>>(inter,rows*I);if(!linear_mixed(m,inter,p(x+12),p(x+13),tmp,rows,I,D))return false;layer_norm<<<rows,128,0,m->stream>>>(tmp,b,a,p(x+14),p(x+15),rows);}
    cls_l2<<<batch,128,0,m->stream>>>(a,m->result,batch,seq);return ok(cudaGetLastError());
}
bool launch_fp32(Model* m,int batch,int seq,int rows,size_t dn){
    auto p=[&](int i){return (float*)m->p[i];};float* a=(float*)m->a;float* b=(float*)m->b;float* q=(float*)m->q;float* k=(float*)m->k;float* v=(float*)m->v;float* merged=(float*)m->merged;float* tmp=(float*)m->tmp;float* inter=(float*)m->inter;
    embeddings<<<(dn+255)/256,256,0,m->stream>>>(m->di,m->dt,tmp,p(0),p(1),p(2),batch,seq);layer_norm<<<rows,128,0,m->stream>>>(tmp,(float*)nullptr,a,p(3),p(4),rows);
    for(int layer=0;layer<LAYERS;layer++){int x=5+layer*16;if(!linear_fp32(m,a,p(x),p(x+1),q,rows,D,D)||!linear_fp32(m,a,p(x+2),p(x+3),k,rows,D,D)||!linear_fp32(m,a,p(x+4),p(x+5),v,rows,D,D))return false;fused_attention<<<batch*H*seq,128,0,m->stream>>>(q,k,v,m->dm,merged,batch,seq);if(!linear_fp32(m,merged,p(x+6),p(x+7),tmp,rows,D,D))return false;layer_norm<<<rows,128,0,m->stream>>>(tmp,a,b,p(x+8),p(x+9),rows);if(!linear_fp32(m,b,p(x+10),p(x+11),inter,rows,D,I))return false;gelu<<<((size_t)rows*I+255)/256,256,0,m->stream>>>(inter,rows*I);if(!linear_fp32(m,inter,p(x+12),p(x+13),tmp,rows,I,D))return false;layer_norm<<<rows,128,0,m->stream>>>(tmp,b,a,p(x+14),p(x+15),rows);}cls_l2<<<batch,128,0,m->stream>>>(a,m->result,batch,seq);return ok(cudaGetLastError());
}
bool launch_pipeline(Model* m,int batch,int seq,int rows,size_t dn){if(m->precision==FP16)return launch_typed<__half>(m,batch,seq,rows,dn);if(m->precision==BF16)return launch_typed<__nv_bfloat16>(m,batch,seq,rows,dn);return launch_fp32(m,batch,seq,rows,dn);}
template<class T> bool launch_diagnostic(Model* m,int batch,int seq,int rows,size_t dn,InvalidValue* invalid,float* snapshots){
    auto p=[&](int i){return (T*)m->p[i];};T* a=(T*)m->a;T* b=(T*)m->b;T* q=(T*)m->q;T* k=(T*)m->k;T* v=(T*)m->v;T* merged=(T*)m->merged;T* tmp=(T*)m->tmp;T* inter=(T*)m->inter;int blocks=(int)((dn+255)/256);auto scan=[&](T* values,size_t count,int stage,int layer){scan_finite<<<(count+255)/256,256,0,m->stream>>>(values,count,invalid,stage,layer);};auto snapshot=[&](int state){if(snapshots)copy_float32<<<blocks,256,0,m->stream>>>(a,snapshots+(size_t)state*dn,dn);};
    embeddings<<<blocks,256,0,m->stream>>>(m->di,m->dt,tmp,p(0),p(1),p(2),batch,seq);scan(tmp,dn,STAGE_EMBEDDINGS,-1);layer_norm<<<rows,128,0,m->stream>>>(tmp,(T*)nullptr,a,p(3),p(4),rows);scan(a,dn,STAGE_EMBEDDING_LN,-1);snapshot(0);
    for(int layer=0;layer<LAYERS;layer++){int x=5+layer*16;if(!linear_any(m,a,p(x),p(x+1),q,rows,D,D)||!linear_any(m,a,p(x+2),p(x+3),k,rows,D,D)||!linear_any(m,a,p(x+4),p(x+5),v,rows,D,D))return false;scan(q,dn,STAGE_Q,layer);scan(k,dn,STAGE_K,layer);scan(v,dn,STAGE_V,layer);fused_attention<<<batch*H*seq,128,0,m->stream>>>(q,k,v,m->dm,merged,batch,seq,invalid,layer);scan(merged,dn,STAGE_CONTEXT,layer);if(!linear_any(m,merged,p(x+6),p(x+7),tmp,rows,D,D))return false;scan(tmp,dn,STAGE_ATTENTION_OUTPUT,layer);layer_norm<<<rows,128,0,m->stream>>>(tmp,a,b,p(x+8),p(x+9),rows);scan(b,dn,STAGE_ATTENTION_LN,layer);if(!linear_any(m,b,p(x+10),p(x+11),inter,rows,D,I))return false;scan(inter,(size_t)rows*I,STAGE_FFN_INPUT,layer);gelu<<<((size_t)rows*I+255)/256,256,0,m->stream>>>(inter,rows*I);scan(inter,(size_t)rows*I,STAGE_GELU,layer);if(!linear_any(m,inter,p(x+12),p(x+13),tmp,rows,I,D))return false;scan(tmp,dn,STAGE_FFN_OUTPUT,layer);layer_norm<<<rows,128,0,m->stream>>>(tmp,b,a,p(x+14),p(x+15),rows);scan(a,dn,STAGE_FFN_LN,layer);snapshot(layer+1);}
    scan(a,(size_t)batch*D,STAGE_CLS,-1);cls_l2<<<batch,128,0,m->stream>>>(a,m->result,batch,seq);scan_finite<<<((size_t)batch*D+255)/256,256,0,m->stream>>>(m->result,(size_t)batch*D,invalid,STAGE_L2,-1);return ok(cudaGetLastError());
}
int expected_count(int index){if(index==0)return 30522*D;if(index==1)return 512*D;if(index==2)return 2*D;if(index<5)return D;int slot=(index-5)%16;if(slot==0||slot==2||slot==4||slot==6)return D*D;if(slot==10)return D*I;if(slot==11)return I;if(slot==12)return I*D;return D;}

uint16_t float_to_bf16(float value){uint32_t bits;std::memcpy(&bits,&value,sizeof(bits));bits+=0x7fffu+((bits>>16u)&1u);return (uint16_t)(bits>>16u);}
float read_le_f32(const uint8_t* data,size_t index){uint32_t bits=(uint32_t)data[index*4]|(uint32_t)data[index*4+1]<<8u|(uint32_t)data[index*4+2]<<16u|(uint32_t)data[index*4+3]<<24u;float value;std::memcpy(&value,&bits,sizeof(value));return value;}
int upload_parameter(Model* m,int index,const uint8_t* data,size_t byte_count,int rows,int columns,bool transpose){
    if(!m||!data||index<0||index>=PARAMS||m->p[index]||rows<1||columns<1)return 1;size_t count=(size_t)expected_count(index);if((size_t)rows>std::numeric_limits<size_t>::max()/(size_t)columns||(size_t)rows*columns!=count||count>std::numeric_limits<size_t>::max()/4||byte_count!=count*4)return 1;
    auto validation_start=std::chrono::steady_clock::now();for(size_t i=0;i<count;i++)if(!std::isfinite(read_le_f32(data,i)))return 1;m->validation_ns+=std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now()-validation_start).count();
    std::vector<float> reordered;const uint8_t* source=data;if(transpose){auto start=std::chrono::steady_clock::now();try{reordered.resize(count);}catch(...){return 2;}constexpr int TILE=32;for(int r0=0;r0<rows;r0+=TILE)for(int c0=0;c0<columns;c0+=TILE)for(int r=r0;r<rows&&r<r0+TILE;r++)for(int c=c0;c<columns&&c<c0+TILE;c++)reordered[(size_t)c*rows+r]=read_le_f32(data,(size_t)r*columns+c);source=(const uint8_t*)reordered.data();m->transpose_ns+=std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now()-start).count();}
    size_t bytes=count*(m->precision==FP32?4u:2u);void* device=nullptr;if(!ok(cudaMalloc(&device,bytes)))return 2;bool copied=false;auto convert_start=std::chrono::steady_clock::now(),upload_start=convert_start;
    if(m->precision==FP32){upload_start=std::chrono::steady_clock::now();copied=ok(cudaMemcpy(device,source,bytes,cudaMemcpyHostToDevice));}
    else if(m->precision==FP16){std::vector<__half> converted;try{converted.resize(count);}catch(...){cudaFree(device);return 2;}for(size_t i=0;i<count;i++)converted[i]=__float2half_rn(transpose?reordered[i]:read_le_f32(data,i));upload_start=std::chrono::steady_clock::now();m->conversion_ns+=std::chrono::duration_cast<std::chrono::nanoseconds>(upload_start-convert_start).count();copied=ok(cudaMemcpy(device,converted.data(),bytes,cudaMemcpyHostToDevice));}
    else{std::vector<uint16_t> converted;try{converted.resize(count);}catch(...){cudaFree(device);return 2;}for(size_t i=0;i<count;i++)converted[i]=float_to_bf16(transpose?reordered[i]:read_le_f32(data,i));upload_start=std::chrono::steady_clock::now();m->conversion_ns+=std::chrono::duration_cast<std::chrono::nanoseconds>(upload_start-convert_start).count();copied=ok(cudaMemcpy(device,converted.data(),bytes,cudaMemcpyHostToDevice));}
    m->upload_ns+=std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now()-upload_start).count();if(!copied){cudaFree(device);return 2;}m->p[index]=device;m->n[index]=count;m->parameter_uploads++;m->parameter_bytes+=bytes;return 0;
}
void* create_model(int precision){if(precision<FP32||precision>BF16)return nullptr;Model* m=new(std::nothrow)Model;if(!m)return nullptr;m->precision=precision;if(!ok(cudaStreamCreateWithFlags(&m->stream,cudaStreamNonBlocking))||!okb(cublasCreate(&m->blas))||!okb(cublasSetStream(m->blas,m->stream))||!okb(cublasSetMathMode(m->blas,CUBLAS_PEDANTIC_MATH))){if(m->blas)cublasDestroy(m->blas);if(m->stream)cudaStreamDestroy(m->stream);delete m;return nullptr;}return m;}
}

extern "C" int cuda_bge_available_impl(){int count=0;return ok(cudaGetDeviceCount(&count))&&count>0;}
extern "C" void* cuda_bge_create_impl(){return create_model(FP32);}extern "C" void* cuda_bge_create_precision_impl(int precision){return create_model(precision);}
extern "C" int cuda_bge_set_parameter_impl(void* handle,int index,const float* data,size_t count){
    return count>std::numeric_limits<size_t>::max()/4?1:upload_parameter((Model*)handle,index,(const uint8_t*)data,count*4,(int)count,1,false);
}
extern "C" int cuda_bge_set_parameter_bytes_impl(void* handle,int index,const uint8_t* data,size_t byte_count,int rows,int columns,int transpose){if(transpose!=0&&transpose!=1)return 1;return upload_parameter((Model*)handle,index,data,byte_count,rows,columns,transpose!=0);}
extern "C" int cuda_bge_finalize_impl(void* handle){Model* m=(Model*)handle;if(!m)return 1;for(void* p:m->p)if(!p)return 1;m->ready=true;return 0;}
extern "C" int cuda_bge_set_math_mode_impl(void* handle,int mode){Model* m=(Model*)handle;if(!m||m->precision!=FP32||(mode!=0&&mode!=1))return 1;cublasMath_t selected=mode==0?CUBLAS_PEDANTIC_MATH:CUBLAS_TF32_TENSOR_OP_MATH;if(!okb(cublasSetMathMode(m->blas,selected)))return 1;if(m->math_mode!=mode)invalidate_graph(m);m->math_mode=mode;return 0;}
extern "C" int cuda_bge_set_graph_enabled_impl(void* handle,int enabled){Model* m=(Model*)handle;if(!m||(enabled!=0&&enabled!=1))return 1;if(m->graph_enabled!=(enabled!=0))invalidate_graph(m);m->graph_enabled=enabled!=0;return 0;}

int cuda_bge_forward_core(void* handle,const int64_t* ids,const uint8_t* mask,const int64_t* types,int batch,int seq,float* host_out,float* timings,int timing_capacity,int* timing_count,float* phase_timings){
    Model* m=(Model*)handle;if(!m||!m->ready||!ids||!mask||!types||!host_out||batch<1||seq<1||seq>512||timings&&m->precision!=FP32)return 1;if((size_t)batch>std::numeric_limits<size_t>::max()/(size_t)seq)return 1;size_t row_count=(size_t)batch*seq;if(row_count>(size_t)std::numeric_limits<int>::max()||row_count>std::numeric_limits<size_t>::max()/D)return 1;int rows=(int)row_count;size_t dn=row_count*D;for(int i=0;i<rows;i++)if(ids[i]<0||ids[i]>=30522||types[i]<0||types[i]>=2)return 1;for(int b=0;b<batch;b++){bool any=false;for(int s=0;s<seq;s++)any=any||mask[b*seq+s]!=0;if(!any)return 1;}
    m->forward_mallocs=0;m->forward_frees=0;m->kernel_launches=195;m->internal_submissions=195;m->h2d_bytes=row_count*17;m->d2h_bytes=(size_t)batch*D*4;m->synchronizations=1;m->last_batch=batch;m->last_seq=seq;m->last_graph_captured=false;m->last_graph_reused=false;if(!ensure_workspace(m,batch,seq))return 2;
    cudaEvent_t events[138]{};int marks=0;if(timings){if(timing_capacity<137||!timing_count)return 1;for(int i=0;i<138;i++)if(!ok(cudaEventCreate(&events[i])))return 2;cudaEventRecord(events[marks++],m->stream);}cudaEvent_t phases[4]{};if(phase_timings){for(int i=0;i<4;i++)if(!ok(cudaEventCreate(&phases[i])))return 2;cudaEventRecord(phases[0],m->stream);}
    #define MARK() if(timings)cudaEventRecord(events[marks++],m->stream)
    if(!ok(cudaMemcpyAsync(m->di,ids,rows*8,cudaMemcpyHostToDevice,m->stream))||!ok(cudaMemcpyAsync(m->dt,types,rows*8,cudaMemcpyHostToDevice,m->stream))||!ok(cudaMemcpyAsync(m->dm,mask,rows,cudaMemcpyHostToDevice,m->stream)))return 2;if(phase_timings)cudaEventRecord(phases[1],m->stream);
    if(!timings&&m->graph_enabled){if(m->graph_exec&&m->graph_batch==batch&&m->graph_seq==seq){if(!ok(cudaGraphLaunch(m->graph_exec,m->stream)))return 2;m->graph_launches++;m->kernel_launches=1;m->last_graph_reused=true;}else if(m->graph_warmed&&m->graph_batch==batch&&m->graph_seq==seq){if(!ok(cudaStreamBeginCapture(m->stream,cudaStreamCaptureModeGlobal))||!launch_pipeline(m,batch,seq,rows,dn))return 2;cudaGraph_t graph{};if(!ok(cudaStreamEndCapture(m->stream,&graph)))return 2;cudaGraphExec_t exec{};if(!ok(cudaGraphInstantiate(&exec,graph,nullptr,nullptr,0))){cudaGraphDestroy(graph);return 2;}invalidate_graph(m);m->graph=graph;m->graph_exec=exec;m->graph_batch=batch;m->graph_seq=seq;m->graph_warmed=true;m->graph_captures++;if(!ok(cudaGraphLaunch(exec,m->stream)))return 2;m->graph_launches++;m->kernel_launches=1;m->last_graph_captured=true;}else{invalidate_graph(m);m->graph_batch=batch;m->graph_seq=seq;m->graph_warmed=true;if(!launch_pipeline(m,batch,seq,rows,dn))return 2;}}
    else if(!timings){if(!launch_pipeline(m,batch,seq,rows,dn))return 2;}
    else{float* a=(float*)m->a;float* b=(float*)m->b;float* q=(float*)m->q;float* k=(float*)m->k;float* v=(float*)m->v;float* merged=(float*)m->merged;float* tmp=(float*)m->tmp;float* inter=(float*)m->inter;auto p=[&](int i){return(float*)m->p[i];};MARK();embeddings<<<(dn+255)/256,256,0,m->stream>>>(m->di,m->dt,tmp,p(0),p(1),p(2),batch,seq);MARK();layer_norm<<<rows,128,0,m->stream>>>(tmp,(float*)nullptr,a,p(3),p(4),rows);MARK();for(int layer=0;layer<LAYERS;layer++){int x=5+layer*16;if(!linear_fp32(m,a,p(x),p(x+1),q,rows,D,D))return 2;MARK();if(!linear_fp32(m,a,p(x+2),p(x+3),k,rows,D,D))return 2;MARK();if(!linear_fp32(m,a,p(x+4),p(x+5),v,rows,D,D))return 2;MARK();fused_attention<<<batch*H*seq,128,0,m->stream>>>(q,k,v,m->dm,merged,batch,seq);MARK();MARK();if(!linear_fp32(m,merged,p(x+6),p(x+7),tmp,rows,D,D))return 2;MARK();layer_norm<<<rows,128,0,m->stream>>>(tmp,a,b,p(x+8),p(x+9),rows);MARK();if(!linear_fp32(m,b,p(x+10),p(x+11),inter,rows,D,I))return 2;MARK();gelu<<<((size_t)rows*I+255)/256,256,0,m->stream>>>(inter,rows*I);MARK();if(!linear_fp32(m,inter,p(x+12),p(x+13),tmp,rows,I,D))return 2;MARK();layer_norm<<<rows,128,0,m->stream>>>(tmp,b,a,p(x+14),p(x+15),rows);MARK();}cls_l2<<<batch,128,0,m->stream>>>(a,m->result,batch,seq);MARK();}
    if(phase_timings)cudaEventRecord(phases[2],m->stream);if(!ok(cudaMemcpyAsync(host_out,m->result,(size_t)batch*D*4,cudaMemcpyDeviceToHost,m->stream)))return 2;MARK();if(phase_timings)cudaEventRecord(phases[3],m->stream);if(!ok(cudaStreamSynchronize(m->stream)))return 2;if(timings){*timing_count=marks-1;for(int i=0;i<marks-1;i++)cudaEventElapsedTime(&timings[i],events[i],events[i+1]);for(int i=0;i<marks;i++)cudaEventDestroy(events[i]);}if(phase_timings){for(int i=0;i<3;i++)cudaEventElapsedTime(&phase_timings[i],phases[i],phases[i+1]);for(auto event:phases)cudaEventDestroy(event);}return 0;
}
extern "C" int cuda_bge_forward_impl(void* h,const int64_t* i,const uint8_t* m,const int64_t* t,int b,int s,float* o){return cuda_bge_forward_core(h,i,m,t,b,s,o,nullptr,0,nullptr,nullptr);}extern "C" int cuda_bge_profile_impl(void* h,const int64_t* i,const uint8_t* m,const int64_t* t,int b,int s,float* o,float* times,int cap,int* count){return cuda_bge_forward_core(h,i,m,t,b,s,o,times,cap,count,nullptr);}extern "C" int cuda_bge_forward_detailed_impl(void* h,const int64_t* i,const uint8_t* m,const int64_t* t,int b,int s,float* o,float* phases){return phases?cuda_bge_forward_core(h,i,m,t,b,s,o,nullptr,0,nullptr,phases):1;}
extern "C" int cuda_bge_diagnose_impl(void* handle,const int64_t* ids,const uint8_t* mask,const int64_t* types,int batch,int seq,float* host_snapshots,size_t snapshot_count,uint64_t* metadata,float* invalid_value){
    Model* m=(Model*)handle;if(!m||!m->ready||!ids||!mask||!types||!metadata||!invalid_value||batch<1||seq<1||seq>512)return 1;if((size_t)batch>std::numeric_limits<size_t>::max()/(size_t)seq)return 1;size_t rows=(size_t)batch*seq;if(rows>std::numeric_limits<size_t>::max()/D)return 1;size_t dn=rows*D;if(dn>std::numeric_limits<size_t>::max()/13||((host_snapshots==nullptr)!=(snapshot_count==0))||(host_snapshots&&snapshot_count!=dn*13)||rows>(size_t)std::numeric_limits<int>::max())return 1;for(size_t i=0;i<rows;i++)if(ids[i]<0||ids[i]>=30522||types[i]<0||types[i]>=2)return 1;for(int b=0;b<batch;b++){bool any=false;for(int s=0;s<seq;s++)any=any||mask[b*seq+s]!=0;if(!any)return 1;}if(!ensure_workspace(m,batch,seq))return 2;
    InvalidValue* device_invalid=nullptr;float* device_snapshots=nullptr;if(!ok(cudaMalloc(&device_invalid,sizeof(InvalidValue)))||(host_snapshots&&!ok(cudaMalloc(&device_snapshots,snapshot_count*sizeof(float))))){cudaFree(device_invalid);cudaFree(device_snapshots);return 2;}InvalidValue zero{};bool success=ok(cudaMemcpyAsync(m->di,ids,rows*8,cudaMemcpyHostToDevice,m->stream))&&ok(cudaMemcpyAsync(m->dt,types,rows*8,cudaMemcpyHostToDevice,m->stream))&&ok(cudaMemcpyAsync(m->dm,mask,rows,cudaMemcpyHostToDevice,m->stream))&&ok(cudaMemcpyAsync(device_invalid,&zero,sizeof(zero),cudaMemcpyHostToDevice,m->stream));if(success){if(m->precision==FP16)success=launch_diagnostic<__half>(m,batch,seq,(int)rows,dn,device_invalid,device_snapshots);else if(m->precision==BF16)success=launch_diagnostic<__nv_bfloat16>(m,batch,seq,(int)rows,dn,device_invalid,device_snapshots);else success=launch_diagnostic<float>(m,batch,seq,(int)rows,dn,device_invalid,device_snapshots);}InvalidValue result{};if(success&&host_snapshots)success=ok(cudaMemcpyAsync(host_snapshots,device_snapshots,snapshot_count*4,cudaMemcpyDeviceToHost,m->stream));if(success)success=ok(cudaMemcpyAsync(&result,device_invalid,sizeof(result),cudaMemcpyDeviceToHost,m->stream))&&ok(cudaStreamSynchronize(m->stream));cudaFree(device_invalid);cudaFree(device_snapshots);if(!success)return 2;metadata[0]=(uint64_t)result.category;metadata[1]=(uint64_t)result.stage;metadata[2]=(uint64_t)(result.layer+1);metadata[3]=result.index;*invalid_value=result.value;return 0;
}
extern "C" void cuda_bge_destroy_impl(void* handle){Model* m=(Model*)handle;if(!m)return;release_workspace(m);for(void* p:m->p)if(p)cudaFree(p);if(m->blas)cublasDestroy(m->blas);if(m->stream)cudaStreamDestroy(m->stream);delete m;}extern "C" int cuda_bge_memory_info_impl(size_t* free_bytes,size_t* total_bytes){return free_bytes&&total_bytes&&ok(cudaMemGetInfo(free_bytes,total_bytes))?0:1;}
extern "C" int cuda_bge_diagnostics_impl(void* handle,uint64_t* values,size_t capacity){Model* m=(Model*)handle;if(!m||!values||capacity<25)return 1;uint64_t result[25]={m->forward_mallocs,m->forward_frees,m->kernel_launches,m->parameter_uploads,m->workspace_reallocations,m->h2d_bytes,m->d2h_bytes,m->synchronizations,m->graph_launches,m->internal_submissions,m->graph_captures,m->graph_invalidations,(uint64_t)m->last_batch,(uint64_t)m->last_seq,(uint64_t)m->graph_enabled,(uint64_t)m->last_graph_captured,(uint64_t)m->last_graph_reused,(uint64_t)(m->graph_exec!=nullptr),m->parameter_bytes,m->workspace_bytes,(uint64_t)m->precision,m->conversion_ns,m->upload_ns,m->validation_ns,m->transpose_ns};for(int i=0;i<25;i++)values[i]=result[i];return 0;}
